name: install-and-test
on: [push]

# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
# `contents` is for permission to the contents of the repository.
# `pull-requests` is for permission to pull request
permissions:
  contents: write
  checks: write
  pull-requests: write

env:
  UV_INDEX_URL: https://gitlab.mpcdf.mpg.de/api/v4/projects/2187/packages/pypi/simple
  UV_SYSTEM_PYTHON: 1

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - uses: hynek/setup-cached-uv@v2
      - name: Install dependencies
        run: |
          uv sync --extra dev
      - name: mypy
        run: |
          uv run mypy --ignore-missing-imports --follow-imports=silent --no-strict-optional src/nomad_simulations tests
      - name: Build coverage file
        run: |
          uv run --with coveralls pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=src tests
      - name: Submit to coveralls
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          uv run coveralls --service=github
  build-and-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - uses: hynek/setup-cached-uv@v2
      - name: Build the package
        run: |
          uv pip install build
          python -m build --sdist
      - name: Install the package
        run: |
          uv pip install dist/*.tar.gz
  ruff-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          args: "check ."
  ruff-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          args: "format . --check --verbose"
